const colours = require("./colours-vars.json");

module.exports = {
  colours,
  customProperties: {
    "--validere-colour": colours.validereColour,
    "--link-colour": colours.linkColour,
    "--navLink-colour": colours.navLinkColour,
    "--navButton-colour": colours.navButtonColour,
    "--sidebarText-colour": colours.sidebarTextColour,
    "--sidebarBackground-colour": colours.sidebarBackgroundColour,
    "--light-text-colour": colours.lightTextColour,
    "--statusCompletedColour": colours.statusCompletedColour,
    "--statusPendingColour": colours.statusPendingColour,
    "--statusErrorColour": colours.statusErrorColour,
    "--borderColour": colours.borderColour,
    "--menuHighlightColour": colours.menuHighlightColour,
    "--menuItemColour": colours.menuItemColour,
    "--disabledFontColour": colours.disabledFontColour,
    "--buttonFocusColour": colours.buttonFocusColour,
    "--alarmColour": colours.alarmColour,
    "--textColour": colours.textColour,
    "--disabledRowColour": colours.disabledRowColour,

    "--colour-primary-50": colours.primary["50"],
    "--colour-primary-100": colours.primary["100"],
    "--colour-primary-200": colours.primary["200"],
    "--colour-primary-300": colours.primary["300"],
    "--colour-primary-400": colours.primary["400"],
    "--colour-primary-500": colours.primary["500"],
    "--colour-primary-600": colours.primary["600"],
    "--colour-primary-700": colours.primary["700"],
    "--colour-primary-800": colours.primary["800"],
    "--colour-primary-900": colours.primary["900"],

    "--colour-white": "#FFFFFF",

    "--colour-text-0": colours.text["000"],
    "--colour-text-100": colours.text["100"],
    "--colour-text-200": colours.text["200"],
    "--colour-text-300": colours.text["300"],
    "--colour-text-400": colours.text["400"],
    "--colour-text-500": colours.text["500"],
    "--colour-text-600": colours.text["600"],
    "--colour-text-700": colours.text["700"],
    "--colour-text-800": colours.text["800"],
    "--colour-text-900": colours.text["900"],

    "--colour-success": colours.status.success,
    "--colour-success-light": colours.status.successLight,
    "--colour-warning": colours.status.warning,
    "--colour-warning-light": colours.status.warningLight,
    "--colour-error": colours.status.error,
    "--colour-error-light": colours.status.errorLight,
    "--colour-default": colours.status.default,
    "--colour-default-light": colours.status.defaultLight,

    "--colour-background": colours.background.default,
    "--colour-background-light": colours.background.white,
    "--colour-background-dark": colours.background.dark,
    "--colour-background-lines": colours.background.lines,

    "--colour-surface": colours.surface.default,
    "--colour-surface-light": colours.surface.light,
    "--colour-surface-dark": colours.surface.dark,
  },
};
